# ignore all warnings from all pods
inhibit_all_warnings!

pod 'Parse', '~> 1.6'
pod 'ParseCrashReporting', '~> 1.7'
pod 'SAMHUDView', '~> 0.1'
pod 'Facebook-iOS-SDK', '~> 3.23'
pod 'ParseFacebookUtils', '~> 1.6'
pod 'Reachability', '~> 3.2'
pod 'SDWebImage', '~> 3.7'
pod 'MagicalRecord', '~> 2.2'
pod 'KissXML', '~> 5.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'hpple', '~> 0.2'
pod 'MWFeedParser'
pod 'UIImage-Categories', '~> 1.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'TestFairy', '~> 1.4'